return {
  ["workshop-1185229307"]={
    ["configuration_options"]={
      [""]="",
      ["DAMAGE_NUMBERS"]=true,
      ["DAMAGE_RESISTANCE"]=true,
      ["FRAME_PHASES"]=true,
      ["HORIZONTAL_OFFSET"]=0,
      ["NOEPIC"]=false,
      ["NONOEPIC"]=false,
      ["WETNESS_METER"]=false 
    },
    ["enabled"]=true 
  },
  ["workshop-1207269058"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-1216718131"]={
    ["configuration_options"]={ ["clean"]=true, ["lang"]=true, ["stack"]=true },
    ["enabled"]=true 
  },
  ["workshop-1418746242"]={
    ["configuration_options"]={ ["clearfont"]=true, ["eventplus"]=true, ["extratrans"]=true },
    ["enabled"]=true 
  },
  ["workshop-1595631294"]={
    ["configuration_options"]={
      ["BundleItems"]=false,
      ["ChangeSkin"]=true,
      ["Digornot"]=false,
      ["DragonflyChest"]=false,
      ["Icebox"]=false,
      ["SaltBox"]=false 
    },
    ["enabled"]=true 
  },
  ["workshop-1951468597"]={
    ["configuration_options"]={
      ["CanSpawnSpore"]=true,
      ["HouseHammered"]=true,
      ["NewInteriors"]=true,
      ["NewWalls"]=true,
      ["Tardis"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-1992058716"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-1998081438"]={
    ["configuration_options"]={ ["StackMode"]=true, ["StackRadius"]=10 },
    ["enabled"]=true 
  },
  ["workshop-2078243581"]={
    ["configuration_options"]={
      ["Blue"]=0,
      ["Display"]="target",
      ["Green"]=0,
      ["Projectile"]=true,
      ["Red"]=1,
      ["Type"]="hit" 
    },
    ["enabled"]=true 
  },
  ["workshop-2119742489"]={
    ["configuration_options"]={ ["Hunger_Cost"]=1, ["Ownership"]=false, ["Sanity_Cost"]=1 },
    ["enabled"]=true 
  },
  ["workshop-2287303119"]={
    ["configuration_options"]={
      [""]=0,
      ["T_crop"]=true,
      ["chestB"]=-1,
      ["chestG"]=-1,
      ["chestR"]=-1,
      ["display_hp"]=1,
      ["food_estimation"]=-1,
      ["food_order"]=0,
      ["food_style"]=0,
      ["item_info_mod"]=0,
      ["lang"]="Auto",
      ["show_buddle_item"]=1,
      ["show_food_units"]=-1,
      ["show_uses"]=-1 
    },
    ["enabled"]=true 
  },
  ["workshop-2427481232"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-2477889104"]={
    ["configuration_options"]={
      ["BADGE_BG_BRIGHTNESS"]=60,
      ["BADGE_BG_OPACITY"]=100,
      ["COLOR_DOMESTICATION_DEFAULT"]="WHITE",
      ["COLOR_DOMESTICATION_ORNERY"]="ORANGE",
      ["COLOR_DOMESTICATION_PUDGY"]="PURPLE",
      ["COLOR_DOMESTICATION_RIDER"]="BLUE",
      ["COLOR_OBEDIENCE"]="RED",
      ["COLOR_TIMER"]="GREEN",
      ["ClientConfig"]=false,
      ["EnableSounds"]=false,
      ["GapModifier"]=0,
      ["HEALTH_BADGE_CLEAR_BG"]=false,
      ["HungerThreshold"]=10,
      ["OffsetX"]=0,
      ["OffsetXFine"]=0,
      ["OffsetXMult"]=1,
      ["OffsetY"]=0,
      ["OffsetYFine"]=0,
      ["OffsetYMult"]=1,
      ["SEPARATOR_BADGE_COLORS"]=1,
      ["SEPARATOR_BADGE_SETTINGS"]=1,
      ["SEPARATOR_GENERAL"]=1,
      ["SEPARATOR_POSITIONING_X"]=1,
      ["SEPARATOR_POSITIONING_Y"]=1,
      ["Scale"]=1,
      ["ShowByDefault"]=true,
      ["Theme"]="TheForge",
      ["ToggleKey"]="KEY_T" 
    },
    ["enabled"]=true 
  },
  ["workshop-2510473186"]={
    ["configuration_options"]={
      ["antlion"]=true,
      ["atrium_gate_cooldown"]=true,
      ["atrium_gate_destable"]=true,
      ["bearger"]=true,
      ["beequeenhive"]=true,
      ["bossposX"]=250,
      ["bossposY"]=80,
      ["crabking_spawner"]=true,
      ["deerclops"]=true,
      ["dragonfly_spawner"]=true,
      ["fontsize"]=17,
      ["fruitfly"]=false,
      ["houndposX"]=80,
      ["houndposY"]=80,
      ["klaus"]=true,
      ["malbatross"]=true,
      ["null"]=0,
      ["prioritytype"]="leasttimefirst",
      ["showname"]=false,
      ["toadstool"]=true,
      ["widgetalign"]="lefttop",
      ["widgetheight"]=80,
      ["widgetwidth"]=80 
    },
    ["enabled"]=true 
  },
  ["workshop-2577742416"]={
    ["configuration_options"]={
      ["ENABLEPINGS"]=true,
      ["FIREOPTIONS"]=2,
      ["OVERRIDEMODE"]=false,
      ["SHAREMINIMAPPROGRESS"]=true,
      ["SHOWFIREICONS"]=true,
      ["SHOWPLAYERICONS"]=true,
      ["SHOWPLAYERSOPTIONS"]=2 
    },
    ["enabled"]=true 
  },
  ["workshop-2784048339"]={
    ["configuration_options"]={
      ["Craft"]="Easy",
      ["Destroyable"]="DestroyByPlayer",
      ["Language"]="Ch",
      ["Slots"]=160,
      ["srfresh"]=0,
      ["sroom_drag"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-2843097516"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-2966979495"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-661253977"]={
    ["configuration_options"]={
      ["amudiao"]=true,
      ["baodiao"]=1,
      ["kong"]=0,
      ["nillots"]=0,
      ["rendiao"]=2,
      ["zbdiao"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-676297854"]={
    ["configuration_options"]={
      ["campfire"]=true,
      ["coldfire"]=true,
      ["coldfirepit"]=true,
      ["deluxe_firepit"]=true,
      ["endo_firepit"]=true,
      ["fire_rez_health_level"]="default",
      ["fire_rez_health_penalty"]=0,
      ["fire_rez_hunger_level"]="default",
      ["fire_rez_lighting_strike_on_rez"]=true,
      ["fire_rez_sanity_level"]="default",
      ["fire_rez_spawn_skelly"]=true,
      ["firepit"]=true,
      ["heat_star"]=true,
      ["ice_star"]=true,
      ["null_option"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-785295023"]={
    ["configuration_options"]={
      ["bossres"]=true,
      ["companion"]=true,
      ["dist"]=2.5,
      ["healthmul"]=-1,
      ["language"]="AUTO",
      ["minimapicon"]=false,
      ["ownership"]=0,
      ["rebounddmg"]=0,
      ["recipe"]="normal",
      ["recipe_door"]=true,
      ["recipe_fence"]=true,
      ["recipe_tool"]=true,
      ["recipe_vanilla"]=false,
      ["recipe_wall"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-875994715"]={ ["configuration_options"]={  }, ["enabled"]=true } 
}